# Generated by Django 4.2.6 on 2023-10-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0002_pedidoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='numero_De_Pieza',
        ),
    ]
