# Generated by Django 4.2.6 on 2023-10-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='catalogo/images/')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=999)),
                ('numeroDePieza', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=51)),
                ('existencias', models.CharField(max_length=50)),
                ('conteoFisico', models.CharField(max_length=50)),
                ('categoria', models.IntegerField(choices=[[0, 'Comunicacion'], [1, 'Seguridad'], [2, 'Educacion'], [3, 'Microcontroladores'], [4, 'Accesorios']])),
                ('nivel', models.IntegerField(choices=[[0, 'Nivel 1'], [1, 'Nivel 2'], [3, 'Nivel 3']])),
                ('seccion', models.IntegerField(choices=[[0, 'Rack A'], [1, 'Rack B'], [2, 'Rack C'], [3, 'Rack D'], [4, 'Rack E'], [5, 'Rack F'], [6, 'Rack G'], [7, 'Rack H']])),
            ],
        ),
    ]
