# Generated by Django 4.2.6 on 2023-10-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='conteoFisico',
            new_name='conteo_Fisico',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='numeroDePieza',
            new_name='numero_De_Pieza',
        ),
    ]
