# Generated by Django 4.2.6 on 2023-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_conteofisico_producto_conteo_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_De_Pieza',
            field=models.BigIntegerField(),
        ),
    ]
