# Generated by Django 4.2.6 on 2023-11-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_producto_numero_de_pieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='conteo_Fisico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_De_Pieza',
            field=models.CharField(max_length=100),
        ),
    ]
